name: Publish Release

on:
  push:
    tags:
      - 'v*-binary'  # This will trigger the workflow when a tag matching 'v*' pattern is pushed

jobs:
  publish_release:
    runs-on: macos-14  # Use macOS runner for macOS/Xcode environment
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.0
      - name: Build Binaries
        run: iOS/archive_xcframework.sh
      - name: Compute Checksum
        id: checksum
        run: |
          echo "checksum=$(swift package compute-checksum ./archives/MMKV.xcframework.zip)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          body: |
            ```swift
            .binaryTarget(
                name: "MMKV",
                url: "https://github.com/Kyle-Ye/MMKV/releases/download/v1.3.5-binary/MMKV.xcframework.zip",
                checksum: "${{ steps.checksum.outputs.checksum }}"
            ),
            ```
          allowUpdates: true
          artifacts: "archives/MMKV.xcframework.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
